/* ============ 内置数据库 ============ */

/* 四级核心词汇库（word, 释义）——每日推送 20 个，循环使用 */
const WORDS = [
["abandon","v. 放弃；抛弃"],["absolute","a. 绝对的；完全的"],["absorb","v. 吸收；使专心"],["abstract","a. 抽象的 n. 摘要"],["abundant","a. 丰富的；充裕的"],
["academic","a. 学术的；学院的"],["accelerate","v. 加速；促进"],["access","n. 通道；机会 v. 访问"],["accommodate","v. 容纳；使适应"],["accompany","v. 陪伴；伴随"],
["accomplish","v. 完成；实现"],["account","n. 账户；描述 v. 解释"],["accumulate","v. 积累；堆积"],["accurate","a. 准确的；精确的"],["accuse","v. 指责；控告"],
["achieve","v. 达到；完成"],["acknowledge","v. 承认；致谢"],["acquire","v. 获得；学到"],["adapt","v. 适应；改编"],["adequate","a. 足够的；胜任的"],
["adjust","v. 调整；适应"],["administration","n. 管理；行政部门"],["admire","v. 钦佩；欣赏"],["admit","v. 承认；准许进入"],["adopt","v. 采纳；收养"],
["advance","v./n. 前进；进展"],["advantage","n. 优势；有利条件"],["adventure","n. 冒险；奇遇"],["advocate","v. 提倡 n. 拥护者"],["affect","v. 影响；感动"],
["afford","v. 负担得起；提供"],["agency","n. 代理机构；作用"],["aggressive","a. 侵略的；有进取心的"],["alternative","n. 替代方案 a. 供选择的"],["ambition","n. 雄心；抱负"],
["amount","n. 数量 v. 合计"],["analyze","v. 分析；解析"],["ancient","a. 古代的；古老的"],["announce","v. 宣布；声称"],["annual","a. 每年的 n. 年刊"],
["anticipate","v. 预期；期望"],["anxiety","n. 焦虑；渴望"],["apparent","a. 明显的；表面的"],["appeal","v./n. 呼吁；吸引"],["applicant","n. 申请人"],
["appreciate","v. 感激；欣赏"],["approach","v. 接近 n. 方法"],["appropriate","a. 适当的"],["approve","v. 赞成；批准"],["approximately","ad. 大约；近似地"],
["arbitrary","a. 任意的；专断的"],["argue","v. 争论；主张"],["arise","v. 出现；起因于"],["arrange","v. 安排；整理"],["artificial","a. 人造的；虚假的"],
["aspect","n. 方面；外观"],["assemble","v. 集合；装配"],["assess","v. 评估；估价"],["assign","v. 分配；指派"],["assist","v. 帮助；协助"],
["associate","v. 联系 n. 同事"],["assume","v. 假定；承担"],["assure","v. 保证；使确信"],["astonish","v. 使惊讶"],["attach","v. 附上；使依恋"],
["attain","v. 达到；获得"],["attempt","v./n. 尝试；企图"],["attitude","n. 态度；看法"],["attract","v. 吸引；引起"],["attribute","v. 归因于 n. 属性"],
["audience","n. 观众；听众"],["authority","n. 权威；当局"],["automatic","a. 自动的"],["available","a. 可用的；有空的"],["average","a. 平均的 n. 平均数"],
["avoid","v. 避免；回避"],["aware","a. 意识到的"],["awkward","a. 尴尬的；笨拙的"],["balance","n. 平衡；余额"],["barrier","n. 障碍；屏障"],
["basis","n. 基础；根据"],["behalf","n. 利益（on behalf of 代表）"],["behavior","n. 行为；举止"],["beneficial","a. 有益的"],["benefit","n. 利益 v. 受益"],
["bias","n. 偏见 v. 使有偏见"],["boost","v./n. 提高；促进"],["border","n. 边界 v. 接壤"],["bother","v. 打扰；烦恼"],["boundary","n. 边界；分界线"],
["brief","a. 简短的 n. 摘要"],["brilliant","a. 杰出的；灿烂的"],["budget","n. 预算 v. 编预算"],["burden","n. 负担 v. 使负重"],["calculate","v. 计算；估计"],
["campaign","n. 运动；战役"],["candidate","n. 候选人；应试者"],["capable","a. 有能力的"],["capacity","n. 容量；能力"],["capture","v. 捕获；夺取"],
["career","n. 职业；生涯"],["casual","a. 随便的；偶然的"],["category","n. 种类；范畴"],["cautious","a. 谨慎的"],["cease","v. 停止；终止"],
["celebrate","v. 庆祝；赞美"],["challenge","n./v. 挑战；质疑"],["characteristic","n. 特征 a. 独特的"],["charge","v. 收费；指控 n. 费用"],["circumstance","n. 环境；情况"],
["cite","v. 引用；举例"],["claim","v. 声称；索取"],["classify","v. 分类；归类"],["climate","n. 气候；风气"],["collapse","v./n. 倒塌；崩溃"],
["colleague","n. 同事"],["combine","v. 结合；联合"],["comment","n./v. 评论；意见"],["commercial","a. 商业的 n. 广告"],["commit","v. 犯（错）；承诺"],
["community","n. 社区；团体"],["compare","v. 比较；对照"],["compensate","v. 补偿；赔偿"],["compete","v. 竞争；比赛"],["competent","a. 有能力的；胜任的"],
["complain","v. 抱怨；投诉"],["complex","a. 复杂的 n. 综合体"],["complicated","a. 复杂的；难懂的"],["component","n. 组成部分；部件"],["comprehensive","a. 全面的；综合的"],
["compromise","n./v. 妥协；折中"],["concentrate","v. 集中；专心"],["concept","n. 概念；观念"],["concern","n. 关心；忧虑 v. 涉及"],["conclude","v. 得出结论；结束"],
["concrete","a. 具体的 n. 混凝土"],["conduct","v. 进行；指挥 n. 行为"],["confidence","n. 信心；信任"],["confirm","v. 证实；确认"],["conflict","n./v. 冲突；矛盾"],
["confront","v. 面对；对抗"],["confuse","v. 使困惑；混淆"],["conquer","v. 征服；克服"],["conscious","a. 意识到的；有意的"],["consequence","n. 结果；后果"],
["conservative","a. 保守的"],["considerable","a. 相当大的"],["consist","v. 组成；一致"],["consistent","a. 一致的；始终如一的"],["constant","a. 不变的；持续的"],
["construct","v. 建造；构成"],["consult","v. 咨询；查阅"],["consume","v. 消耗；消费"],["contact","n./v. 接触；联系"],["contemporary","a. 当代的；同时代的"],
["content","n. 内容 a. 满足的"],["contest","n. 比赛 v. 竞争"],["context","n. 上下文；背景"],["continual","a. 不断的；频繁的"],["contract","n. 合同 v. 收缩"],
["contrary","a. 相反的 n. 反面"],["contrast","n./v. 对比；对照"],["contribute","v. 贡献；投稿"],["controversial","a. 有争议的"],["convenient","a. 方便的"],
["conventional","a. 传统的；常规的"],["convert","v. 转变；转换"],["convey","v. 传达；运送"],["convince","v. 使确信；说服"],["cooperate","v. 合作；配合"],
["cope","v. 应付；处理"],["corporate","a. 公司的；共同的"],["correspond","v. 相符；通信"],["crash","v./n. 碰撞；崩溃"],["create","v. 创造；引起"],
["credit","n. 信用；学分"],["crisis","n. 危机；紧要关头"],["criterion","n. 标准；准则"],["critical","a. 批评的；关键的"],["crucial","a. 至关重要的"],
["cultivate","v. 培养；耕作"],["curious","a. 好奇的；奇特的"],["current","a. 当前的 n. 水流"],["curriculum","n. 课程"],["cycle","n. 循环；周期"],
["debate","n./v. 辩论；争论"],["decade","n. 十年"],["decent","a. 体面的；正派的"],["declare","v. 宣布；申报"],["decline","v./n. 下降；拒绝"],
["decorate","v. 装饰；布置"],["dedicate","v. 奉献；致力于"],["defend","v. 保卫；辩护"],["deficiency","n. 缺乏；不足"],["define","v. 定义；限定"],
["definite","a. 明确的；肯定的"],["delay","v./n. 延迟；耽搁"],["deliberate","a. 故意的；深思熟虑的"],["deliver","v. 递送；发表"],["demand","n./v. 要求；需求"],
["demonstrate","v. 证明；示威"],["dense","a. 密集的；浓厚的"],["deny","v. 否认；拒绝"],["depict","v. 描绘；描述"],["deposit","n. 存款；押金 v. 存放"],
["depress","v. 使沮丧；使萧条"],["derive","v. 源于；获得"],["descend","v. 下降；遗传"],["describe","v. 描述；形容"],["deserve","v. 应得；值得"],
["designate","v. 指定；指派"],["desirable","a. 值得拥有的；可取的"],["desperate","a. 绝望的；不顾一切的"],["destination","n. 目的地"],["destruction","n. 破坏；毁灭"],
["detail","n. 细节 v. 详述"],["detect","v. 察觉；侦查"],["determine","v. 决定；确定"],["device","n. 装置；设备"],["devote","v. 致力于；奉献"],
["digital","a. 数字的"],["dimension","n. 尺寸；维度"],["diminish","v. 减少；缩小"],["disaster","n. 灾难；不幸"],["discipline","n. 纪律；学科"],
["discount","n. 折扣 v. 打折"],["dismiss","v. 解雇；驳回"],["display","v./n. 展示；陈列"],["dispose","v. 处理；布置"],["dispute","n./v. 争论；纠纷"],
["distinct","a. 明显的；不同的"],["distinguish","v. 区分；辨别"],["distribute","v. 分发；分布"],["disturb","v. 打扰；扰乱"],["diverse","a. 多样的；不同的"],
["domestic","a. 国内的；家庭的"],["dominate","v. 支配；占优势"],["donate","v. 捐赠；捐献"],["draft","n. 草稿 v. 起草"],["dramatic","a. 戏剧性的；显著的"],
["durable","a. 耐用的；持久的"],["dynamic","a. 动态的；有活力的"],["eager","a. 渴望的；热切的"],["economic","a. 经济的"],["edit","v. 编辑；剪辑"],
["effective","a. 有效的"],["efficient","a. 高效的"],["elaborate","a. 精心的 v. 详述"],["elderly","a. 年长的"],["elect","v. 选举；选择"],
["element","n. 元素；成分"],["eliminate","v. 消除；淘汰"],["embarrass","v. 使尴尬"],["embrace","v. 拥抱；接受"],["emerge","v. 出现；浮现"],
["emergency","n. 紧急情况"],["emotion","n. 情感；情绪"],["emphasize","v. 强调；着重"],["employ","v. 雇用；使用"],["enable","v. 使能够"],
["encounter","v./n. 遇到；遭遇"],["encourage","v. 鼓励；促进"],["endure","v. 忍受；持续"],["engage","v. 从事；订婚"],["enhance","v. 提高；增强"],
["enormous","a. 巨大的"],["ensure","v. 确保；保证"],["enterprise","n. 企业；事业心"],["entertainment","n. 娱乐；款待"],["enthusiasm","n. 热情；热心"],
["entire","a. 全部的；整个的"],["entitle","v. 使有资格；命名"],["environment","n. 环境"],["equip","v. 装备；配备"],["equivalent","a. 等价的 n. 等价物"],
["essential","a. 必要的；本质的"],["establish","v. 建立；确立"],["estimate","v./n. 估计；评价"],["evaluate","v. 评估；评价"],["eventually","ad. 最终；终于"],
["evidence","n. 证据；迹象"],["evident","a. 明显的"],["evolve","v. 进化；发展"],["exaggerate","v. 夸大；夸张"],["exceed","v. 超过；胜过"],
["exchange","v./n. 交换；交流"],["exclude","v. 排除；不包括"],["excursion","n. 短途旅行"],["executive","n. 主管 a. 执行的"],["exhaust","v. 使精疲力尽 n. 废气"],
["exhibit","v. 展出 n. 展品"],["expand","v. 扩大；膨胀"],["expense","n. 费用；开支"],["experiment","n./v. 实验；试验"],["expert","n. 专家 a. 熟练的"],
["explicit","a. 明确的；清楚的"],["explore","v. 探索；探究"],["expose","v. 暴露；揭露"],["extend","v. 延伸；扩展"],["external","a. 外部的"],
["extraordinary","a. 非凡的；特别的"],["extreme","a. 极端的 n. 极端"],["facility","n. 设施；设备"],["factor","n. 因素；要素"],["faculty","n. 才能；全体教员"],
["fade","v. 褪色；逐渐消失"],["failure","n. 失败；故障"],["faithful","a. 忠实的；可靠的"],["familiar","a. 熟悉的"],["fascinating","a. 迷人的"],
["fatigue","n. 疲劳"],["favorable","a. 有利的；赞成的"],["feasible","a. 可行的"],["feature","n. 特征 v. 以…为特色"],["federal","a. 联邦的"],
["feedback","n. 反馈"],["fertile","a. 肥沃的；多产的"],["figure","n. 数字；人物 v. 认为"],["finance","n. 财政；金融 v. 资助"],["flexible","a. 灵活的；柔韧的"],
["flourish","v. 繁荣；茂盛"],["fluctuate","v. 波动；起伏"],["fluent","a. 流利的"],["focus","v./n. 集中；焦点"],["forecast","v./n. 预测；预报"],
["formal","a. 正式的"],["former","a. 以前的 n. 前者"],["formula","n. 公式；配方"],["fortune","n. 财富；运气"],["forum","n. 论坛"],
["foundation","n. 基础；基金会"],["fragile","a. 易碎的；脆弱的"],["framework","n. 框架；结构"],["frequent","a. 频繁的"],["frustrate","v. 使沮丧；挫败"],
["fulfill","v. 履行；实现"],["function","n. 功能 v. 运转"],["fundamental","a. 基本的；根本的"],["furthermore","ad. 此外；而且"],["gap","n. 差距；缺口"],
["generate","v. 产生；发电"],["generous","a. 慷慨的；大方的"],["genuine","a. 真正的；真诚的"],["gesture","n. 手势；姿态"],["glimpse","n./v. 一瞥"],
["global","a. 全球的；全面的"],["gradual","a. 逐渐的"],["grant","v. 授予 n. 拨款"],["grateful","a. 感激的"],["guarantee","v./n. 保证；担保"],
["handle","v. 处理 n. 把手"],["harsh","a. 严酷的；刺耳的"],["hesitate","v. 犹豫；踌躇"],["highlight","v. 突出 n. 亮点"],["hollow","a. 空心的；空洞的"],
["horizon","n. 地平线；眼界"],["household","n. 家庭 a. 家用的"],["identical","a. 完全相同的"],["identify","v. 识别；认同"],["ignore","v. 忽视；不理睬"],
["illustrate","v. 说明；图解"],["imitate","v. 模仿；仿效"],["immense","a. 巨大的"],["immigrant","n. 移民"],["impact","n./v. 影响；冲击"],
["implement","v. 实施 n. 工具"],["imply","v. 暗示；意味着"],["impose","v. 强加；征收"],["impress","v. 给…留下印象"],["incident","n. 事件；事变"],
["incline","v. 倾向于；倾斜"],["income","n. 收入"],["incredible","a. 难以置信的"],["indicate","v. 表明；指示"],["individual","a. 个人的 n. 个体"],
["industry","n. 工业；勤奋"],["inevitable","a. 不可避免的"],["infer","v. 推断；推理"],["inferior","a. 较差的；下级的"],["influence","n./v. 影响"],
["inform","v. 通知；告知"],["ingredient","n. 成分；原料"],["inhabitant","n. 居民"],["inherit","v. 继承"],["initial","a. 最初的 n. 首字母"],
["initiative","n. 主动性；倡议"],["innovation","n. 创新；革新"],["insight","n. 洞察力；见解"],["inspire","v. 鼓舞；启发"],["install","v. 安装；安置"],
["instance","n. 例子；实例"],["instinct","n. 本能；直觉"],["institute","n. 学院 v. 制定"],["instruction","n. 指示；教学"],["instrument","n. 仪器；乐器"],
["insurance","n. 保险"],["intact","a. 完整无缺的"],["integrate","v. 使一体化；结合"],["intellectual","a. 智力的 n. 知识分子"],["intelligence","n. 智力；情报"],
["intend","v. 打算；意图"],["intense","a. 强烈的；紧张的"],["interact","v. 互动；相互作用"],["internal","a. 内部的"],["interpret","v. 解释；口译"],
["interrupt","v. 打断；中断"],["interval","n. 间隔；幕间休息"],["intimate","a. 亲密的"],["invest","v. 投资；投入"],["investigate","v. 调查；研究"],
["involve","v. 涉及；卷入"],["isolate","v. 隔离；孤立"],["issue","n. 问题；发行 v. 发布"],["justify","v. 证明…正当"],["keen","a. 敏锐的；渴望的"],
["label","n. 标签 v. 贴标签"],["laboratory","n. 实验室"],["launch","v. 发射；发起"],["leak","v./n. 泄漏"],["lease","n./v. 租约；出租"],
["legal","a. 法律的；合法的"],["legislation","n. 立法；法规"],["leisure","n. 闲暇；悠闲"],["liberal","a. 自由的；开明的"],["license","n. 执照 v. 许可"],
["likewise","ad. 同样地"],["limitation","n. 限制；局限"],["literally","ad. 字面上；确实地"],["literature","n. 文学；文献"],["load","n. 负载 v. 装载"],
["locate","v. 定位；位于"],["logical","a. 逻辑的；合理的"],["loyal","a. 忠诚的"],["luxury","n. 奢侈；奢侈品"],["maintain","v. 维持；保养"],
["major","a. 主要的 n. 专业"],["manage","v. 管理；设法做到"],["manual","a. 手工的 n. 手册"],["manufacture","v./n. 制造"],["margin","n. 边缘；利润"],
["massive","a. 大量的；巨大的"],["mature","a. 成熟的 v. 成熟"],["measure","v. 测量 n. 措施"],["mechanism","n. 机制；机械装置"],["media","n. 媒体"],
["medium","n. 媒介 a. 中等的"],["mental","a. 精神的；智力的"],["mention","v./n. 提到；提及"],["merchant","n. 商人"],["mere","a. 仅仅的"],
["merge","v. 合并；融合"],["method","n. 方法；条理"],["minimum","n. 最小值 a. 最低的"],["minor","a. 较小的 n. 未成年人"],["mission","n. 使命；任务"],
["mobile","a. 移动的"],["moderate","a. 适度的；温和的"],["modify","v. 修改；缓和"],["monitor","v. 监控 n. 显示器"],["motivate","v. 激励；激发"],
["multiple","a. 多样的；多重的"],["mutual","a. 相互的；共同的"],["native","a. 本地的 n. 本地人"],["navigate","v. 导航；驾驶"],["negative","a. 消极的；否定的"],
["neglect","v./n. 忽视；疏忽"],["negotiate","v. 谈判；协商"],["nevertheless","ad. 然而；不过"],["notion","n. 概念；想法"],["numerous","a. 众多的"],
["objective","n. 目标 a. 客观的"],["obligation","n. 义务；责任"],["observe","v. 观察；遵守"],["obstacle","n. 障碍；妨碍"],["obtain","v. 获得；得到"],
["obvious","a. 明显的"],["occasion","n. 场合；时机"],["occupy","v. 占据；占用"],["occur","v. 发生；出现"],["offend","v. 冒犯；违反"],
["opponent","n. 对手；反对者"],["opportunity","n. 机会"],["oppose","v. 反对；对抗"],["optimistic","a. 乐观的"],["option","n. 选择；选项"],
["organize","v. 组织；安排"],["origin","n. 起源；出身"],["outcome","n. 结果；成果"],["output","n. 产量；输出"],["overcome","v. 克服；战胜"],
["overlook","v. 忽略；俯瞰"],["overseas","a./ad. 海外的（地）"],["overwhelm","v. 压倒；淹没"],["participate","v. 参加；参与"],["particular","a. 特定的；特别的"],
["passion","n. 激情；热情"],["patent","n. 专利 a. 明显的"],["pattern","n. 模式；图案"],["peculiar","a. 奇特的；独特的"],["perceive","v. 感知；认为"],
["permanent","a. 永久的"],["persist","v. 坚持；持续"],["perspective","n. 视角；观点"],["persuade","v. 说服；劝说"],["phase","n. 阶段；方面"],
["phenomenon","n. 现象"],["philosophy","n. 哲学；人生观"],["physical","a. 身体的；物理的"],["policy","n. 政策；保险单"],["portion","n. 部分；一份"],
["positive","a. 积极的；肯定的"],["possess","v. 拥有；具有"],["potential","a. 潜在的 n. 潜力"],["practical","a. 实际的；实用的"],["precise","a. 精确的"],
["predict","v. 预测；预言"],["prefer","v. 更喜欢"],["prejudice","n. 偏见"],["preliminary","a. 初步的；预备的"],["presence","n. 出席；存在"],
["preserve","v. 保护；保存"],["pressure","n. 压力"],["prevail","v. 盛行；获胜"],["previous","a. 以前的"],["primary","a. 主要的；初级的"],
["principle","n. 原则；原理"],["priority","n. 优先；优先权"],["privilege","n. 特权；荣幸"],["procedure","n. 程序；步骤"],["proceed","v. 继续进行"],
["process","n. 过程 v. 处理"],["profession","n. 职业；专业"],["profit","n. 利润 v. 获益"],["prohibit","v. 禁止"],["project","n. 项目 v. 投射"],
["prominent","a. 突出的；杰出的"],["promote","v. 促进；晋升"],["prompt","a. 迅速的 v. 促使"],["proportion","n. 比例；部分"],["propose","v. 提议；求婚"],
["prospect","n. 前景；展望"],["prosperity","n. 繁荣；兴旺"],["protest","n./v. 抗议；反对"],["psychology","n. 心理学；心理"],["publish","v. 出版；发表"],
["purchase","v./n. 购买"],["pursue","v. 追求；从事"],["qualify","v. 使合格；取得资格"],["quantity","n. 数量"],["quote","v. 引用 n. 报价"],
["random","a. 随机的；任意的"],["range","n. 范围 v. 变动"],["rare","a. 稀有的；罕见的"],["rational","a. 理性的；合理的"],["react","v. 反应；反抗"],
["recall","v. 回忆；召回"],["recognize","v. 认出；承认"],["recommend","v. 推荐；建议"],["recover","v. 恢复；痊愈"],["recruit","v. 招募 n. 新兵"],
["reduce","v. 减少；降低"],["refer","v. 提到；参考"],["reflect","v. 反映；反思"],["reform","n./v. 改革；改进"],["refresh","v. 使恢复精神；刷新"],
["regard","v. 认为 n. 尊重"],["region","n. 地区；区域"],["register","v./n. 登记；注册"],["regulate","v. 管理；调节"],["reinforce","v. 加强；增援"],
["reject","v. 拒绝；抛弃"],["relate","v. 联系；讲述"],["relevant","a. 相关的"],["reliable","a. 可靠的"],["relieve","v. 缓解；减轻"],
["reluctant","a. 不情愿的"],["rely","v. 依赖；依靠"],["remark","n./v. 评论；话语"],["remarkable","a. 显著的；非凡的"],["remedy","n. 补救；药物"],
["remote","a. 遥远的；偏僻的"],["remove","v. 移除；搬迁"],["render","v. 使成为；提供"],["represent","v. 代表；表现"],["reputation","n. 名声；声誉"],
["request","n./v. 请求；要求"],["require","v. 需要；要求"],["research","n./v. 研究；调查"],["resemble","v. 像；类似"],["reserve","v. 预订 n. 储备"],
["resident","n. 居民 a. 居住的"],["resist","v. 抵抗；抗拒"],["resolve","v. 解决；决心"],["resource","n. 资源；财力"],["respond","v. 回应；响应"],
["restore","v. 恢复；修复"],["restrict","v. 限制；约束"],["retain","v. 保留；保持"],["retire","v. 退休；退出"],["retreat","v./n. 撤退；退却"],
["reveal","v. 揭示；透露"],["revenue","n. 收入；税收"],["reverse","v. 颠倒 n. 相反"],["review","v./n. 复习；评论"],["revise","v. 修订；复习"],
["reward","n. 报酬 v. 奖励"],["rigid","a. 僵硬的；严格的"],["rough","a. 粗糙的；大致的"],["routine","n. 常规 a. 例行的"],["rural","a. 农村的"],
["sacrifice","n./v. 牺牲；献祭"],["satisfy","v. 使满意；满足"],["scale","n. 规模；刻度"],["scarce","a. 缺乏的；稀有的"],["schedule","n. 时间表 v. 安排"],
["scheme","n. 计划；方案"],["scope","n. 范围；余地"],["secure","a. 安全的 v. 获得"],["seek","v. 寻求；追求"],["segment","n. 部分；片段"],
["select","v. 选择；挑选"],["sensible","a. 明智的；合理的"],["sensitive","a. 敏感的；灵敏的"],["sequence","n. 顺序；序列"],["session","n. 会议；一段时间"],
["settle","v. 解决；定居"],["severe","a. 严重的；严厉的"],["shift","v./n. 转移；轮班"],["shortage","n. 短缺；不足"],["shrink","v. 收缩；缩小"],
["significant","a. 重要的；显著的"],["similar","a. 相似的"],["simulate","v. 模拟；假装"],["simultaneously","ad. 同时地"],["slight","a. 轻微的；纤细的"],
["solution","n. 解决方案；溶液"],["sophisticated","a. 复杂的；老练的"],["source","n. 来源；水源"],["spare","a. 空闲的 v. 抽出"],["specific","a. 具体的；特定的"],
["spectacular","a. 壮观的"],["speculate","v. 推测；投机"],["spirit","n. 精神；心灵"],["split","v. 分裂 n. 裂口"],["sponsor","n. 赞助者 v. 赞助"],
["spontaneous","a. 自发的；自然的"],["stable","a. 稳定的"],["standard","n. 标准 a. 标准的"],["statistics","n. 统计；统计学"],["status","n. 地位；状态"],
["steady","a. 稳定的；稳固的"],["stimulate","v. 刺激；激励"],["strategy","n. 战略；策略"],["strengthen","v. 加强；巩固"],["stress","n. 压力 v. 强调"],
["strict","a. 严格的"],["structure","n. 结构 v. 构建"],["struggle","v./n. 挣扎；奋斗"],["subsequent","a. 随后的"],["substantial","a. 大量的；实质的"],
["substitute","n. 替代品 v. 代替"],["subtle","a. 微妙的；精细的"],["suburb","n. 郊区"],["sufficient","a. 足够的；充分的"],["summary","n. 摘要；总结"],
["superior","a. 优越的 n. 上级"],["supplement","n./v. 补充；增补"],["suppress","v. 压制；抑制"],["surgery","n. 外科手术"],["surplus","n. 剩余 a. 过剩的"],
["survey","n./v. 调查；测量"],["survive","v. 幸存；活下来"],["suspect","v. 怀疑 n. 嫌疑人"],["suspend","v. 暂停；悬挂"],["sustain","v. 维持；支撑"],
["symbol","n. 符号；象征"],["sympathy","n. 同情；共鸣"],["symptom","n. 症状；征兆"],["target","n. 目标 v. 瞄准"],["technical","a. 技术的；专业的"],
["temporary","a. 临时的；暂时的"],["tendency","n. 趋势；倾向"],["tension","n. 紧张；张力"],["terminal","n. 终点站 a. 末端的"],["territory","n. 领土；领域"],
["theme","n. 主题"],["theory","n. 理论；学说"],["thorough","a. 彻底的；仔细的"],["threat","n. 威胁；恐吓"],["thrive","v. 繁荣；茁壮成长"],
["tolerate","v. 容忍；忍受"],["trace","v. 追踪 n. 痕迹"],["tradition","n. 传统；惯例"],["transfer","v./n. 转移；换乘"],["transform","v. 改变；转化"],
["transmit","v. 传输；传播"],["transparent","a. 透明的；显然的"],["transport","v./n. 运输"],["tremendous","a. 巨大的；极好的"],["trend","n. 趋势；潮流"],
["trigger","v. 触发 n. 扳机"],["ultimate","a. 最终的；根本的"],["undergo","v. 经历；遭受"],["undertake","v. 承担；从事"],["uniform","n. 制服 a. 一致的"],
["unique","a. 独特的；唯一的"],["universal","a. 普遍的；宇宙的"],["update","v./n. 更新"],["urban","a. 城市的"],["urge","v. 敦促 n. 冲动"],
["urgent","a. 紧急的"],["utilize","v. 利用"],["vacant","a. 空的；空缺的"],["valid","a. 有效的；合理的"],["vanish","v. 消失；突然不见"],
["variety","n. 多样性；种类"],["vast","a. 巨大的；广阔的"],["vehicle","n. 车辆；工具"],["venture","n. 冒险事业 v. 冒险"],["version","n. 版本；说法"],
["vertical","a. 垂直的"],["victim","n. 受害者；牺牲品"],["vigorous","a. 有力的；精力充沛的"],["violate","v. 违反；侵犯"],["virtual","a. 虚拟的；实际上的"],
["visible","a. 可见的；明显的"],["vision","n. 视力；远见"],["vital","a. 至关重要的"],["vivid","a. 生动的；鲜艳的"],["voluntary","a. 自愿的"],
["vulnerable","a. 脆弱的；易受伤的"],["welfare","n. 福利；幸福"],["widespread","a. 广泛的；普遍的"],["withdraw","v. 撤回；取款"],["witness","n. 目击者 v. 见证"],
["worthwhile","a. 值得做的"],["yield","v. 产出；屈服 n. 产量"]
];

/* 四级长短句库（句子、译文、要点解析）——每日推送 3 句 */
const SENTENCES = [
["Not only did the experiment fail, but it also caused unexpected damage to the equipment.","实验不仅失败了，还对设备造成了意想不到的损坏。","Not only 置于句首时句子需部分倒装（did the experiment fail）。"],
["It is widely acknowledged that regular exercise contributes to both physical and mental health.","人们普遍认为，规律锻炼对身心健康都有益。","It is acknowledged that... 形式主语结构，写作常用句式。"],
["Only when we lose something do we realize how precious it is.","只有当我们失去某样东西时，才会意识到它有多珍贵。","Only + 状语从句置于句首，主句部分倒装。"],
["The more you practice speaking English, the more confident you will become.","你练习英语口语越多，就会变得越自信。","The more..., the more... 比较级并列结构。"],
["Faced with fierce competition, many graduates choose to further their studies.","面对激烈的竞争，许多毕业生选择继续深造。","过去分词短语 Faced with... 作状语，逻辑主语是句子主语。"],
["There is no denying that technology has dramatically changed the way we communicate.","不可否认，科技极大地改变了我们的交流方式。","There is no denying that... 固定句型；the way 后接定语从句可省略 in which。"],
["What matters is not what happens to you, but how you respond to it.","重要的不是发生了什么，而是你如何应对。","What 引导主语从句和表语从句，not...but... 并列。"],
["Despite the fact that he had little experience, he managed to complete the project on time.","尽管经验不足，他还是设法按时完成了项目。","despite + 名词/the fact that 从句；manage to do 表示成功做成。"],
["It was not until midnight that she finished writing her report.","直到午夜她才写完报告。","It was not until... that... 强调句型，注意不倒装。"],
["Scientists have found that people who sleep less than six hours are more likely to gain weight.","科学家发现，睡眠不足六小时的人更容易发胖。","who 引导定语从句修饰 people；be likely to do 表可能性。"],
["Had I known the truth earlier, I would have made a different decision.","要是我早点知道真相，我就会做出不同的决定。","省略 if 的虚拟条件句，Had I known = If I had known。"],
["The government has taken effective measures to reduce air pollution, which benefits everyone.","政府已采取有效措施减少空气污染，这让每个人都受益。","which 引导非限制性定语从句，指代前面整句话。"],
["As is often the case, success comes to those who are well prepared.","正如通常情况那样，成功属于有准备的人。","As is often the case 非限制性定语从句，as 指代主句内容。"],
["So rapidly is technology developing that we can hardly keep up with it.","科技发展如此之快，我们几乎跟不上它的步伐。","so + 副词置于句首引起部分倒装；so...that... 结果状语从句。"],
["Whether we can achieve the goal depends largely on how well we cooperate.","我们能否实现目标很大程度上取决于我们合作得如何。","whether 引导主语从句；how well 引导宾语从句。"],
["The reason why he was late was that his car broke down on the way.","他迟到的原因是车在路上抛锚了。","reason 后接 why 定语从句，表语从句用 that 而非 because。"],
["Compared with traditional media, social media spreads information much faster.","与传统媒体相比，社交媒体传播信息要快得多。","Compared with... 过去分词短语作状语，表比较。"],
["It is high time that we paid attention to the problem of food safety.","是我们关注食品安全问题的时候了。","It is high time that + 过去式（虚拟语气）。"],
["Those who never give up are more likely to succeed in the end.","永不放弃的人最终更有可能成功。","Those who... 固定搭配，表示“……的人们”。"],
["Judging from his accent, he must come from the southern part of the country.","从口音判断，他一定来自这个国家的南方。","Judging from... 独立成分，不受逻辑主语限制。"],
["The lecture was so boring that half of the audience fell asleep.","讲座太无聊了，一半听众都睡着了。","so + 形容词 + that 结果状语从句。"],
["With the development of the economy, people's living standards have improved remarkably.","随着经济的发展，人民生活水平显著提高。","With + 名词短语作伴随状语，写作高频句式。"],
["He devoted all his spare time to helping the children in remote mountain areas.","他把所有业余时间都投入到帮助偏远山区的孩子上。","devote...to doing，to 是介词后接动名词。"],
["No matter how difficult the task is, we should never lose heart.","无论任务多么困难，我们都不应灰心。","No matter how + 形容词 + 主谓，让步状语从句。"],
["The problem is not whether we should do it, but when and how we should do it.","问题不在于我们是否应该做，而在于何时以及如何做。","not...but... 并列表语从句。"],
["A growing number of young people prefer working in big cities to staying in their hometowns.","越来越多的年轻人宁愿在大城市工作也不愿留在家乡。","prefer doing A to doing B 固定搭配。"],
["It never occurred to me that such a quiet man could be so brave in an emergency.","我从未想到这样一个安静的人在紧急情况下会如此勇敢。","It occurred to sb. that... 固定句型，“某人想到……”。"],
["The company attaches great importance to the training of its new employees.","这家公司非常重视新员工的培训。","attach importance to 固定搭配，“重视”。"],
["Nowhere else in the world can you find such magnificent scenery.","在世界其他任何地方你都找不到如此壮丽的风景。","否定副词 Nowhere 置于句首引起部分倒装。"],
["Taking regular breaks while studying helps improve concentration and memory.","学习时定期休息有助于提高专注力和记忆力。","动名词短语作主语，谓语用单数。"],
["The survey conducted last month reveals that most students are under great pressure.","上个月进行的调查显示大多数学生压力很大。","过去分词 conducted 作后置定语修饰 survey。"],
["However tired he was, he insisted on finishing the work before going to bed.","无论多累，他都坚持睡前完成工作。","However + 形容词引导让步状语从句；insist on doing。"],
["One of the biggest challenges facing modern society is the aging of the population.","现代社会面临的最大挑战之一是人口老龄化。","现在分词 facing 作后置定语；one of + 复数名词。"],
["It makes no difference whether you come today or tomorrow, as long as you come.","你今天来还是明天来没有区别，只要你来就行。","It 作形式主语代替 whether 从句；as long as 引导条件从句。"],
["Believe it or not, reading aloud is one of the most effective ways to learn a language.","信不信由你，大声朗读是学习语言最有效的方法之一。","Believe it or not 插入语；one of the most... 最高级结构。"],
["Much as I admire his courage, I don't think he made the right decision.","尽管我很钦佩他的勇气，但我认为他的决定并不正确。","Much as = Although，引导让步状语从句。"],
["The moment she stepped onto the stage, the audience burst into applause.","她一登上舞台，观众就爆发出掌声。","The moment 引导时间状语从句，相当于 as soon as。"],
["What impressed me most about the city was its perfect combination of tradition and modernity.","这座城市最让我印象深刻的是传统与现代的完美结合。","What 引导主语从句；impress sb. most 固定搭配。"],
["Every possible means has been tried, but none of them worked.","所有可能的办法都试过了，但没有一个奏效。","means 单复数同形；every + 单数概念，谓语用单数。"],
["If it had not been for your timely help, we would not have finished the task.","要不是你的及时帮助，我们不可能完成任务。","If it had not been for... 虚拟语气，“要不是……”。"],
["The number of people who choose to work remotely has increased sharply in recent years.","近年来选择远程工作的人数急剧增加。","The number of + 复数名词作主语，谓语用单数。"],
["Hardly had he arrived at the station when the train started to move.","他刚到车站，火车就开动了。","Hardly...when... 倒装句型，主句用过去完成时。"]
];

/* 基金学习课程（12 课） */
const FUND_LESSONS = [
{t:"什么是基金？",c:"基金是把众多投资者的钱集中起来，交给专业基金经理投资的工具。按投资标的分为：货币基金（余额宝类，风险最低）、债券基金、混合基金、股票基金、指数基金（风险依次升高，预期收益也升高）。"},
{t:"认识风险与收益",c:"收益和风险永远成正比。货币基金年化约1.5-2%，债基约3-5%，股票/指数基金长期年化可能7-12%但波动大，短期可能亏20%以上。先问自己：亏15%会不会睡不着？"},
{t:"指数基金入门",c:"指数基金跟踪某个指数（如沪深300、中证500、恒生指数），费率低、透明、不依赖基金经理个人能力，是新手最推荐的品种。巴菲特多次推荐普通人定投指数基金。"},
{t:"什么是定投？",c:"定期定额投资，如每月发工资后投1000元。核心作用：平摊成本、克服追涨杀跌的人性弱点。适合有稳定现金流的上班族。定投最怕中途放弃，跌的时候恰恰是攒便宜筹码的时候。"},
{t:"基金费率详解",c:"申购费（买入时，多数平台1折约0.15%）、赎回费（持有<7天惩罚性1.5%，尽量持有>30天）、管理费+托管费（每年约0.5-1.5%，从净值中扣）。长期持有，费率差1%，十年差出一部大手机。"},
{t:"如何挑选基金",c:"看5点：①成立>3年 ②规模2-100亿之间 ③基金经理任职>3年且业绩稳定 ④同类排名长期前1/3 ⑤最大回撤自己能承受。不要只看近1年涨幅冠军，冠军魔咒很常见。"},
{t:"资产配置入门",c:"经典公式：股票类仓位 = (100 - 年龄)%。更实用的三笔钱：①活钱（3-6个月生活费，货基）②稳健钱（1-3年要用，债基/固收+）③长期钱（3年以上不用，股票/指数基金）。"},
{t:"止盈的艺术",c:"定投止盈常用方法：①目标收益法：达到15-30%分批止盈 ②估值法：指数进入高估区间分批卖出 ③最大回撤法：从最高点回撤超8-10%止盈。止盈后继续下一轮定投，不要空仓等待。"},
{t:"看懂基金估值",c:"常用指标：PE（市盈率）百分位。某指数当前PE处于历史30%分位以下算低估（适合多买），70%以上算高估（考虑止盈）。支付宝/天天基金都有指数红绿灯工具。"},
{t:"常见坑与心态",c:"①追热点行业基金（新能源、白酒教训） ②频繁买卖交手续费 ③满仓单一行业 ④借钱投资 ⑤看到跌就割肉。记住：基金赚钱的前提是拿得住，时间是好公司的朋友。"},
{t:"债基与固收+",c:"债券基金波动小，适合稳健钱。纯债基金只投债券；固收+以债券打底（约80%），少量股票增强收益。选择时注意：回撤<3%、成立>2年、规模>5亿。利率上行期债基短期也会小幅回调，属正常。"},
{t:"制定自己的投资体系",c:"完整闭环：①每月工资到账先储蓄后消费 ②按三笔钱分配 ③长期钱定投宽基指数 ④低估多投、高估少投 ⑤达到目标收益分批止盈 ⑥每季度复盘一次。写下来，执行它，不要被市场情绪带偏。"}
];

/* 选题角度模板 */
const TOPIC_TEMPLATES = [
"蹭热点：结合「{hot}」做{domain}视角的快评/盘点",
"深度解读：「{hot}」背后的原因分析，输出观点型内容",
"关联选题：从「{hot}」延伸到{domain}领域的实用干货",
"对比选题：「{hot}」VS 同类事件，做对比盘点",
"教程选题：围绕「{hot}」出一期新手向科普/教程",
"互动选题：就「{hot}」发起投票/评论区互动话题",
"人物角度：挖掘「{hot}」中的人物故事做叙事内容",
"合集选题：把「{hot}」纳入本周{domain}大事件合集"
];

/* 热榜数据源配置 */
const HOT_SOURCES = [
 {key:"weibo", name:"微博热搜", icon:"WB", color:"#e6553a"},
 {key:"douyin", name:"抖音热点", icon:"DY", color:"#170b1a"},
 {key:"zhihu", name:"知乎热榜", icon:"ZH", color:"#0a66d1"},
 {key:"bilibili", name:"B站热门", icon:"BL", color:"#fb7299"},
 {key:"toutiao", name:"头条热榜", icon:"TT", color:"#ee2b25"},
 {key:"baidu", name:"百度热搜", icon:"BD", color:"#2932e1"},
 {key:"36kr", name:"36氪·商业", icon:"KR", color:"#0c6cff"}
];

/* 平台选项 */
const PLATFORMS = ["抖音","小红书","视频号","B站","微博","知乎","快手","公众号","头条","其他"];

/* 健身项目预设 */
const FIT_TYPES = ["跑步","健走","瑜伽","力量训练","跳绳","骑行","游泳","羽毛球","帕梅拉","八段锦","爬山","其他"];

/* AI 探讨的本地引导问题（未配置 API Key 时使用） */
const LOCAL_PROMPTS = [
"这本书里最打动你的一个观点是什么？为什么它触动了你？",
"如果要把这本书的核心思想讲给一个完全没读过的朋友，你会怎么用三句话概括？",
"书中有没有你不认同的地方？试着说说你的反驳理由。",
"这本书的观点和你过去的经验有冲突吗？冲突在哪里？",
"读完这部分，你打算在生活/工作中做出什么具体改变？",
"作者的论证过程中，你觉得最薄弱的一环是什么？",
"如果作者坐在你对面，你最想问TA的一个问题是什么？",
"这本书让你联想到了之前读过的哪本书或哪个理论？它们的关系是什么？"
];
